### PR TITLE
docs: create robust Git exclusions file and format Dashboard README

### LINKED ISSUE #25: docs: update gitignore and use code fences for dashboard
The `.gitignore` in the project is slim. Build out a more robust exclusion file for IDEs, OSs, and tools using gitignore.io templates; initially include exclusions for the following:

* windows (OS)
* macos (OS)
* intellij+all (IDE)
* eclipse (IDE)
* netbeans (IDE)
* visualstudiocode (IDE)
* angular (tool/language)
* node (tool/language)
* helm (tool/language)

In the Dashboard Security `readme.md` use code fences to provide in browser copy and paste provided by GitHub. Additionally, code fences provide execution in some IDEs (like IntelliJ).

### PR DESCRIPTION
**Pull request by timothystone-knsl**
The Git Exclusions in `.gitignore` could be more robust. Use gitignore.io to generate a more inclusive exclusion file with support for common IDEs, OSs, and languages.

Update the README for Dashboard Security with semantic headers and use code fences for supporting features in GitHub and GitLab block copy (browser) and IDE run block features.

Fixes #25

### CODE REVIEW

**Comment by timothystone-knsl** [comment]
@DanWahlin I'm coming to this a bit late, but it's a good course (worth an update). I thought these changes could be helpful for others coming to this on Pluralsight. Copying and pasting these commands are easy with the code fence features and IDEs offer code fence execution features as well.

**Comment by timothystone-knsl** [comment]
~~Also, if you want an issue, let me know. I'll create it and add the appropriate footers to the PR.~~

Opened #25

**Comment by DanWahlin** [comment]
Thanks @timothystone-knsl! Appreciate the updates. Agree that the code fences make it easier for copy/paste.

**Comment by timothystone-knsl** [comment]
> Thanks @timothystone-knsl! Appreciate the updates. Agree that the code fences make it easier for copy/paste.

Any time @DanWahlin. Working through the course in detail (an intentional second time). If not unwelcome, I'll post new PRs as I encounter them. It is a really great introduction through advanced k8s.

**Pull request merged**
